/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#241a00',
        'on-surface': '#d7e3f5',
        'background': '#081421',
        'secondary-container': '#214a7c',
        'on-secondary-fixed': '#001c3a',
        'on-tertiary-container': '#493a00',
        'on-surface-variant': '#d1c5ad',
        'surface-container-low': '#101c29',
        'on-primary-container': '#4b3900',
        'error': '#ffb4ab',
        'surface-container-highest': '#2a3643',
        'surface': '#081421',
        'primary-fixed-dim': '#f0c131',
        'on-secondary': '#00315f',
        'primary': '#f0c131',
        'on-error': '#690005',
        'tertiary': '#e8c33f',
        'on-secondary-fixed-variant': '#1e4879',
        'on-primary-fixed-variant': '#594400',
        'error-container': '#93000a',
        'secondary-fixed-dim': '#a5c8ff',
        'outline': '#9a907a',
        'surface-container-lowest': '#040f1b',
        'on-tertiary-fixed': '#231b00',
        'secondary': '#a5c8ff',
        'inverse-on-surface': '#26313f',
        'on-error-container': '#ffdad6',
        'primary-container': '#cca000',
        'surface-bright': '#2e3a48',
        'inverse-surface': '#d7e3f5',
        'surface-tint': '#f0c131',
        'tertiary-container': '#c5a31d',
        'on-secondary-container': '#95baf3',
        'secondary-fixed': '#d4e3ff',
        'surface-dim': '#081421',
        'surface-container-high': '#1f2b38',
        'on-tertiary': '#3b2f00',
        'on-background': '#d7e3f5',
        'outline-variant': '#4e4634',
        'surface-variant': '#2a3643',
        'inverse-primary': '#755b00',
        'tertiary-fixed-dim': '#e8c33f',
        'surface-container': '#15202d',
        'on-primary': '#3e2e00',
        'primary-fixed': '#ffdf91',
        'tertiary-fixed': '#ffe07e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        unit: '4px',
        xl: '48px',
        lg: '24px',
        'container-max': '1280px',
        xxl: '80px',
        gutter: '24px',
        md: '16px',
        sm: '8px',
      },
      fontFamily: {
        'body-lg': ['Manrope', 'sans-serif'],
        'label-sm': ['Manrope', 'sans-serif'],
        'headline-xl': ['EB Garamond', 'serif'],
        'headline-md': ['EB Garamond', 'serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'display-lg': ['EB Garamond', 'serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.0', letterSpacing: '0.15em', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
